shinyUI(
  fluidPage(
    # Application title
    titlePanel("Benchmark overlap probabilities (BOPs)"),
    hr(),
    #sidebarPanel(width = 4,
    tabsetPanel(
      sidebarPanel(width = 4,
                   div(style="display:inline-block;width:100%",
                       selectInput(inputId = "datainput",
                                   label = "Select between demos or uploading data (template at 3rd panel)",
                                   choices = c("Demos","Data"),
                                   selected = "Demos")),
                   uiOutput("datasets"),
                   hr(),
                   h4("Benchmark general population level: (input for example '0.7' events per 100.000 cases for Erythema)"),
                   uiOutput("reflevel"),
                   hr(),
                   h4("Benchmark relative levels"),
                   div(style="display:inline-block;width:100%",
                       numericInput("rellevel",
                                    label = "Input i.e h = 10 denotes that the upper (lower) event rate equals to 10 (1/10) times the general population rate:",
                                    value = 5,
                                    min = 0.01,
                                    max = 10000,step = 2)),
                   h4("Beta influencial statistic priors"),
                   div(style="display:inline-block;width:100%",
                       sliderInput("X_number",
                                   label = "Add ie.'X' prior cases that separate the two inferences. Default is Pt1 ~ Beta(1,10^6), Pt2 ~ Beta(X,200-X)",
                                   value = 3,
                                   min = 1,
                                   max = 50,step = 1)),
                   h6("Note: Increasing X correspond to more prevalent Pt2 priors, that would lead to more conservative BOP signal deployment."),
                   #h6("Note: By increasing the number to 50, the user assumes prior information of 25 cases for model 1 experiencing the side effect and 25 cases for model 2 not experiencing the side effect"),
                   # div(style="display:inline-block;width:45%",
                   #     sliderInput("br_prior",
                   #                 label = "Beta(,b) prior:",
                   #                 value = 10,
                   #                 min = 1,
                   #                 max = 100,step=1)),
                   hr(),
                   sliderInput("sims",
                               label = "Number of simulations (thousands):",
                               value = 8000,
                               min = 500,
                               max = 20000,
                               step = 500),
                   selectInput(inputId = "typegraph",
                               label = "Line BOPlot or Area BOPlot?",
                               choices = c("Line BOPlot","Area BOPlot"),
                               selected = "Line BOPlot"),
                   selectInput(inputId = "compareT",
                               label = "Add reference line to the BOPlot based on a U(1,1) prevalence prior? (available for the line BOPlot)",
                               choices = c("Yes","No"),
                               selected = "Yes"),
                   hr(),
                   #div(style="display:inline-block;width:45%;text-align: center;",actionButton("demos", "Run analysis"), style="float:center"),
                   h6("Reference: Deleted for peer-review")
                   #Pateras K & Kostoulas P, Not all zeros are equal: Quantifying very rare 
                   #adverse effects via the benchmark overlap probability (0 ≠ 0), 2022, Submitted")
      ),
      mainPanel(tabsetPanel(tabPanel("Graphical inference",
                                     plotOutput("distPlot1")
      ),
      tabPanel("Numeric 'non-informative' inference",
               fluidRow(dataTableOutput("table1"))),
      tabPanel("Template for data input",
               fluidRow(dataTableOutput("table2")))
      ))
      
    )
    # ,
    # tabPanel("Single",
    #          sidebarPanel(width = 4,
    #                       h3("Based on a single sample"),
    #                       # Sidebar with a slider input for number of bins 
    #                       div(style="display:inline-block;width:45%",
    #                           numericInput("events",
    #                                        label = "Number of events:",
    #                                        value = 4,
    #                                        min = 0,
    #                                        max = 10^30)),
    #                       div(style="display:inline-block;width:45%",
    #                           numericInput("sample",
    #                                        label = "Sample size:",
    #                                        value = 1000,
    #                                        min = 1,
    #                                        max = 10^30)),
    #                       hr(),
    #                       h4("Benchmark levels (in thousands)"),
    #                       div(style="display:inline-block;width:45%",
    #                       numericInput("reflevel_single",
    #                                    label = "Reference rate:",
    #                                    value = 0.1,
    #                                    min = 0.01,
    #                                    max = 10000,step = 10)),
    #                       hr(),
    #                       h4("Beta objective prior"),
    #                       div(style="display:inline-block;width:45%",
    #                           sliderInput("ar_prior_single",
    #                                       label = "Beta(a,) prior:",
    #                                       value = 0.1,
    #                                       min = 0.01,
    #                                       max = 1,step = 0.01)),
    #                       div(style="display:inline-block;width:45%",
    #                           sliderInput("br_prior_single",
    #                                       label = "Beta(,b) prior:",
    #                                       value = 10,
    #                                       min = 1,
    #                                       max = 100,step=1)),
    #                       hr(),
    #                       sliderInput("sims_single",
    #                                   label = "Number of simulations (thousands):",
    #                                   value = 800,
    #                                   min = 100,
    #                                   max = 1000,
    #                                   step = 100),
    #                       hr(),
    #                       sliderInput("c",
    #                                   label = "Probability threshold:",
    #                                   value = 0.9,
    #                                   min = 0,
    #                                   max = 1,
    #                                   step = 0.01),
    #                       hr(),                                  
    #                       #div(style="display:inline-block;width:45%;text-align: center;",actionButton("sample", "Run analysis"), style="float:center"),
    #                       h6("Reference: Deleted for peer-review")
    #                       #Pateras K & Kostoulas P, Not all zeros are equal: Quantifying very rare 
    #                       #adverse effects via the benchmark overlap probability (0 ≠ 0), 2022, Submitted")
    #                       
    #          ),
    #          mainPanel(uiOutput("Rmark"))
    #)#,
    # Show a plot of the generated distribution
    ##    mainPanel(
    #       plotOutput("distPlot")
    #  )
  )
)